main: de.timesnake.game.bowrun.main.GameBowRun
version: ${version}
name: game-bowrun
author: timesnake
depend: [ basic-lounge-bridge ]
api-version: 1.21

commands:
  bowrun_verify:
  bowrun_reject:

     